//Jenkins pipeline to build and deploy a Maven project on Tomcat

pipeline {
    // Run the pipeline on any available Jenkins agent
    agent any

    stages {

        // Stage 1: Clone Source Code
        stage('Clone SCM') {
            steps {
                // Clone code from GitHub repository
                echo 'Cloning source code from GitHub...'
                git branch: 'main', url: 'https://github.com/Sandeep-akula-01/mindcircuit16d.git'
            }
        }

        // Stage 2: Build Project
        stage('Build Artifact') {
            steps {
                // Build project using Maven and generate .war file
                echo 'Building project using Maven...'
                sh 'mvn clean install'
            }
        }

        // Stage 3: Deploy to Tomcat
        stage('Deploy to Tomcat') {
            steps {
                // Deploy the .war file to Tomcat server
                echo 'Deploying .war file to Tomcat...'
                deploy adapters: [tomcat9(
                    alternativeDeploymentContext: '',
                    credentialsId: 'tomcat',
                    path: '',
                    url: 'http://43.204.237.107:8080/'
                )],
                contextPath: 'MY_Page',
                war: '**/*.war'
            }
        }
    }
}

