#Jenkins file Updated maven_install

pipeline {

    agent any
	tools {
	maven 'Maven_3.9.11'
	}
    stages {
	
        stage('CLONE SCM') {
            steps {
                echo 'This stage clones SC from GIT repo'				
				git branch: 'main', url: 'https://github.com/Sandeep-akula-01/Java_Project.git'
            }
        }
		
        stage('Build Artifact') {
            steps {
                echo 'This stage builds the code using maven'
				sh 'mvn clean install'			
				
            }
        }
		
        stage('Deploy to Tomcat') {
            steps {
                echo 'This stage deploys .war to tomcat webserver'
                deploy adapters: [tomcat9(alternativeDeploymentContext: '', credentialsId: 'tomcat', path: '', url: 'http://13.232.61.1:8082/')], contextPath: 'JAVA-APP', war: '**/*.war'
            }
        }		
		
    }
}


